Milestone 7: Add forms
zdnahom/blog-app pull request #7
Opened 2023-06-16 08:47 UTC by zdnahom

## Milestone 7: Add forms
In this milestone I :
- Added a method called 'current_user' in ApplicationController 
- Created forms for the below
  - posts(Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).)
  - comments(Create a comment on behalf of the current_user (use the method that you created in your ApplicationController))
  - likes(Allow Users to add likes to Posts.)

2023-06-16 09:58 UTC, emmanuellekamwa requested changes
**STATUS: CHANGES REQUESTED ⛔❌**
Hello @zdnahom 👋
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Descriptive PR.
- Good commit messages.
- Correct git-flow.

## Required Changes ♻️
_Check the comments under the review._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 09:58 UTC, emmanuellekamwa commented on app/controllers/comments_controller.rb
- [ ] The "new" method should not be blank. Use this code `@comment = Comment.new`.

2023-06-16 09:58 UTC, emmanuellekamwa commented on app/controllers/posts_controller.rb
> +
- [ ] The "new" method should not be blank. Use this code `@post = Post.new`.

2023-06-16 10:43 UTC, zdnahom commented on app/controllers/comments_controller.rb
I get what you mean @emmanuellekamwa, I will definitely do that 🙌

2023-06-16 10:44 UTC, zdnahom commented on app/controllers/posts_controller.rb
> +
I will add it @emmanuellekamwa 🙌

2023-06-16 11:08 UTC, zdnahom commented
Thanks for the review @emmanuellekamwa 😉

2023-06-16 11:38 UTC, danmainah approved these changes
Hi @zdnahom , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️  Implemented changes requested, ensuring a suer can add a post comment and like.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 11:38 UTC, danmainah commented on app/views/posts/index.html.erb
> +<% if flash[:notice] %>
- [ ] [optional] @zdnahom great work implementing the changes requested,to make the user experience better, I would suggest you add links, from the root page to take the user to the user show page and another from the user show page to posts page and from posts index page to posts show page.

2023-06-17 12:20 UTC, zdnahom commented
Thanks for the review @danmainah 🙏

2023-06-17 12:21 UTC, zdnahom commented on app/views/posts/index.html.erb
> +<% if flash[:notice] %>
I will do that @danmainah, thanks for the suggestion 😉

2023-06-17 12:21 UTC, merged