Milestone 8: Add integration spec and Solve n+1 problems
zdnahom/blog-app pull request #8
Opened 2023-06-19 22:58 UTC by zdnahom

## Milestone 8: Add integration spec and Solve n+1 problems
In this milestone I :
- Solved n+1 problem on the post index page where we have posts and their comments
  - Before
  
![Screenshot (21)](https://github.com/zdnahom/blog-app/assets/51995150/117a74da-7bf0-4fce-bcf2-e29fd6ca2700)

  - After
  
![Screenshot (22)](https://github.com/zdnahom/blog-app/assets/51995150/de894e71-25b5-48b9-95ad-42b212d22813)

- Did integration tests for the pages
  - User index page:
    - I can see the username of all other users.
    - I can see the profile picture for each user.
    - I can see the number of posts each user has written.
    - When I click on a user, I am redirected to that user's show page.
  - User show page:
    - I can see the user's profile picture.
    - I can see the user's username.
    - I can see the number of posts the user has written.
    - I can see the user's bio.
    - I can see the user's first 3 posts.
    - I can see a button that lets me view all of a user's posts.
    - When I click a user's post, it redirects me to that post's show page.
    - When I click to see all posts, it redirects me to the user's post's index page.
  - User post index page:
    - I can see the user's profile picture.
    - I can see the user's username.
    - I can see the number of posts the user has written.
    - I can see a post's title.
    - I can see some of the post's body.
    - I can see the first comments on a post.
    - I can see how many comments a post has.
    - I can see how many likes a post has.
    - I can see a section for pagination if there are more posts than fit on the view.
    - When I click on a post, it redirects me to that post's show page.
  - Post show page:
    - I can see the post's title.
    - I can see who wrote the post.
    - I can see how many comments it has.
    - I can see how many likes it has.
    - I can see the post body.
    - I can see the username of each commentor.
    - I can see the comment each commentor left.

2023-06-19 23:17 UTC, julie-ify requested changes
## Hi @zdnahom and @gaks1,

Good job so far!

## Highlights!
- Scenarios coverage ✔️
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-19 23:17 UTC, julie-ify commented on spec/integration/post_spec.rb
> +  end
- [ ] **[OPTIONAL]** Kindly separate these post index and show page tests into different files for more code organization. Each view page should have its own file.

2023-06-19 23:17 UTC, julie-ify commented on spec/integration/user_spec.rb
> +  describe 'User show page' do
- [ ] **[OPTIONAL]** Kindly separate these user index and show page tests into different files for more code organization. Each view page should have its own file.

2023-06-19 23:17 UTC, julie-ify commented on spec/integration/user_spec.rb
> +      expect(page).to have_content(user.name)
- [ ] You are displaying only one user. Kindly create more users and show that all the users are being displayed in the index page.

2023-06-19 23:17 UTC, julie-ify commented on spec/integration/user_spec.rb
> +    end
- [ ] Kindly refactor these tests to account for more users, instead of just one user.

2023-06-19 23:48 UTC, zdnahom commented
Thanks for the review @julie-ify , we will fix that 🙌

2023-06-20 01:26 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi team 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Added integration tests 📌 
✔️ Fixed n+1 problem 📌 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 01:26 UTC, codepantha commented on spec/integration/user_index_spec.rb
> +    end
- [ ] Just like the previous reviewer suggested, please refactor these tests to account for more users instead of just one user.
You need to assert that: 
1. you can see the profile picture for each user
2. you can see the number of posts each user has written

### Please see a screenshot from the project requirements below 👇 
![image](https://github.com/zdnahom/blog-app/assets/46839548/62ee0efc-c578-4117-9243-6a66d6dc14f7)

2023-06-20 07:34 UTC, zdnahom commented
Thanks for the feedback @codepantha, we will fix that 👍

2023-06-20 08:19 UTC, Deepakdanger approved these changes
Hi @zdnahom , 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 13:15 UTC, zdnahom commented
Thanks for the review @Deepakdanger 🙌

2023-06-20 13:15 UTC, merged